### ISSUE TITLE
pnpm install with version 8 throws "unsupported engine" error 

### ISSUE THREAD

**Issue by ianldgs** [otahontas/trpc-rtk-query#307]
My current pnpm workspace uses pnpm version 8. Didn't migrate yet because it's a breaking change - v9 uses a different lock file.

When running `pnpm install trpc-rtk-query --engine-strict` it throws the following error:

```
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/trpc-rtk-query/0.1.1(@reduxjs/toolkit@2.2.1)(@trpc/client@10.45.2)(@trpc/server@10.45.2)".

Expected version: >=9
Got: 8.10.5

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
```

It should be completely fine to install `trpc-rtk-query` with other versions of pnpm.

My suggestion: remove the `pnpm` from the `engines` field, and set the `packageManager` field to use [corepack](https://nodejs.org/docs/latest-v20.x/api/corepack.html).

**Comment by ianldgs** [comment]
@otahontas any thoughts on this? Would you accept a PR with the suggested fix?

**Comment by otahontas** [comment]
@ianldgs Hey, good catch, happy to review a PR from you with the fix.
