### ISSUE TITLE
Doesn't install using Yarn

### ISSUE THREAD

**Issue by jonathanrgreene** [otahontas/trpc-rtk-query#35]
I tried to install this with Yarn using:
yarn add trpc-rtk-query@https://github.com/otahontas/trpc-rtk-query.git

But I get this...
Error: trpc-rtk-query@https://github.com/otahontas/trpc-rtk-query.git#commit=1b9aff8a7d5cb3888c726581bedc522a9d5feafb: Assertion failed: Unsupported workflow

**Comment by otahontas** [comment]
Since this wasn't reproducible, I'm closing the issue. Please feel free to open this one again @jonathanrgreene if there are more unexpected issues when using this library with yarn.
