### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by robinellgren** [otahontas/trpc-rtk-query#62]
Wow this library seem so cool! Thank you for writing it 🙏 

I have a client with 8 procedures. These are all flat and not nested in the client.

Yet I am experiencing

```
Type instantiation is excessively deep and possibly infinite.ts(2589)
(alias) createApi<AnyRouter, "api", never, CreateEndpointDefinitions<AnyRouter, TRPCBaseQuery, "api", never>>(options: TRPCClientOptions<AnyRouter> & Omit<...> & {
    ...;
}): Api<...>
import createApi
```

Is there any limits on the amount of procedures one can have in the client? Thanks 👋

**Comment by otahontas** [comment]
Hey and thanks for the kind words and feedback @robinellgren! 

I haven't explicitly tested against how deep a client can be, but 8 procedures seem to be quite a reasonable amount to handle (could add a test for a bit bigger router,  thanks for pointing this one out).

`Type instantiation is excessively deep and possibly` is a quite generic way for typescript compiler to inform you about compiler issues, and isn't itself necessarily tied to your trpc router being too wide. So, to help with debugging, can you first ensure that you have all the correct peer dependency versions installed? This would mean having:

```
@reduxjs/toolkit (minimum 1.9.5)
@trpc/client version (minimum 10.31.0)
@trpc/server version  (minimum 10.31.0)
```
(I also realized that these haven't been pinned to readme, so I'll do that too). Especially take care that the @tprc/client and @tprc/server versions are the same in your frontend and backend!

If this doesn't help, would you be able to provide a reproducible example with for example https://codesandbox.io?

**Comment by robinellgren** [comment]
Thanks for the answer!

I have been fiddling a bit with the version and it seems this is not actually an issue. As long as you are in a monorepo context, the library is working as intended. My usecase is a non-monorepo context in which I export the type for `AppRouter` and have an npm package import it. Then, it seems it does not work. 

It show as `Type instantiation is excessively deep and possible infinite` but it seems the real issue is 
`...is missing the following properties from type 'Router<AnyRouterDef<AnyRootConfig, any>>': _def, createCaller, getErrorShapets(2344)`.

I realise this should no longer be considered a bug, but more like a feature request since you have not mentioned that you support non-monorepo setups. So if you want to close this ticket, it's fine by me.

Anyway, I created a codesandbox if you want to take a look: https://codesandbox.io/s/cool-jepsen-yvx99l

The `createClient.d.ts` is the type I get when I build my trpc server and export the AppRouter type.

**Comment by robinellgren** [comment]
After some more testing, it turns out that updating tRPC client and server in all environments to at least minimum 10.31.0 solves all issues and I am now able to use library. I was using `10.5.0`.

Nevermind the codesandbox.

Thanks for an awesome lib 🎉
